### ISSUE TITLE
Creating an effective call queue

### ISSUE THREAD

**Issue by NedgoIO** [chadsmith/OpenVBX-Plugin-Queue#1]
I can't figure out how to effectively set this up. How do you notify/call an agent when a call is in the queue? Would you have to have someone just sit a refresh the manage queue page till they see one there and then direct it to a flow to dial them? How do you set the maximum time for someone to be in a queue before they are transferred to voice mail?

**Comment by chadsmith** [comment]
I just updated the readme with additional info on what the plugin does and how to use it.

As of right now there's no way to see if an agent is available or notify them a call is in the queue, but you could text them whenever a call is added using my Outbound plugin. I'll see if I can come up with a better solution for that.

The update I just pushed also adds Leave conditions, where the Queue could be exited if a certain criteria is met, such as a time limit or queue length, and an applet that lets you notify the caller of the average wait and their position in the queue.

**Comment by zubairi** [comment]
I want agent pickup any call in the queue. is it possible?
