### ISSUE TITLE
Adding a menu to the queue flow

### ISSUE THREAD

**Issue by NedgoIO** [chadsmith/OpenVBX-Plugin-Queue#2]
I tried to add a simple menu within the wait flow of the queue and it just holds the whole thing up. The caller just sits in silence and the queue doesn't continue past it. All I was trying to do was give the caller the option to just leave a voice mail if they didn't want to wait in the queue. Is there a certain key press already set aside to leave the queue and continue to the next part of en-queue applet?(which in my case would be transferring them to voice mail)

**Comment by NedgoIO** [comment]
Any ideas on this?

**Comment by chadsmith** [comment]
It [looks like](http://www.twilio.com/blog/2013/02/now-ready-using-gather-in-queue-for-call-center-win.html) &lt;Gather>'s weren't supported in &lt;Queue>'s until a couple weeks ago. It should work fine now.

**Comment by NedgoIO** [comment]
Thanks! I'll try to reimplement it again later this evening.
